### PR TITLE
Make code xml schema-independent

### LINKED ISSUE #100: Default nuget schema is wrong
The namespace schema used by the adapter is `http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd`, which ends up in failed attempts to publish a package to a NuGet repository, that is all because the default schema defined by the official NuGet client(version 5.6.0) is `http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd`. 

I think the XML schema should be ignored since we can stick any of existed ones.

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #100

### CODE REVIEW

**Comment by Sammers21** [comment]
@olegmoz, please review the PR.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks, allis good, but could you please add a tests or tests about parsing XML with other schema mentioned in the issue?

**Comment by Sammers21** [comment]
@olegmoz, review the PR once again, please.

File: src/test/java/com/artipie/nuget/NuspecTest.java [hunk 1]
```diff
@@ -55,6 +59,39 @@ void init() throws Exception {
...
+     * @throws Exception If fails
+     * @checkstyle RegexpSingleline (500 lines)
+     * @checkstyle RegexpSinglelineCheck (500 lines)
+     */
+    @Test
+    void shouldExtractPackageIdFromDifPackage() throws Exception {
+        MatcherAssert.assertThat(
+            new Nuspec(
+                ByteSource.wrap(
+                    ("\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>"
```
Comment (olegmoz) [inline src/test/java/com/artipie/nuget/NuspecTest.java:73]: @Sammers21 could you please explain what symbol `\uFEFF` mean? Is it here for a reason?

File: src/test/java/com/artipie/nuget/NuspecTest.java [hunk 2]
```diff
@@ -55,6 +59,39 @@ void init() throws Exception {
...
+                        + "\n    <authors>aripie</authors>"
+                        + "\n    <owners>aripie</owners>"
+                        + "\n    <requireLicenseAcceptance>false</requireLicenseAcceptance>"
+                        + "\n    <description>Sample for a deployment to Artipie</description>"
+                        + "\n    <tags>sample artipie</tags>"
+                        + "\n    <contentFiles>"
+                        + "\n      <files include=\"data.txt\" buildAction=\"Content\" />"
+                        + "\n    </contentFiles>"
+                        + "\n  </metadata>"
+                        + "\n</package>"
```
Comment (olegmoz) [inline src/test/java/com/artipie/nuget/NuspecTest.java:87]: @Sammers21 I'd suggesto to build this XML string using `String.join("\n", ...)` method. This will be more in line with our coding style and will allow to remove `StringLiteralsConcatenationCheck`, `OperatorWrapCheck` warnings

File: src/test/java/com/artipie/nuget/NuspecTest.java [hunk 3]
```diff
@@ -55,6 +59,39 @@ void init() throws Exception {
...
+                    ).getBytes(StandardCharsets.UTF_8)
+                )
+            ).packageId().toString(),
```
Comment (olegmoz) [inline src/test/java/com/artipie/nuget/NuspecTest.java:90]: @Sammers21 method `version` was fixed in this PR as well, I think we should check it in the test as well

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks for adding the test, please see the comments

File: src/test/java/com/artipie/nuget/NuspecTest.java (hunk 2 above)
Comment (Sammers21) [reply src/test/java/com/artipie/nuget/NuspecTest.java:87]: @olegmoz, don't like this idea.

File: src/test/java/com/artipie/nuget/NuspecTest.java (hunk 3 above)
Comment (Sammers21) [reply src/test/java/com/artipie/nuget/NuspecTest.java:90]: @olegmoz, done

**Comment by Sammers21** [comment]
@olegmoz, review the PR once again, please.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 two of my comments from previous review haven't been resolved yet

**Comment by Sammers21** [comment]
@olegmoz, ну не хочу я убирть плюсики. Так все делают и так удобно. Нет разницы почти никакой и не думаю что это принципиально. А первый тот странный символ отправляет нугет клиент как я и писал

File: src/test/java/com/artipie/nuget/NuspecTest.java (hunk 1 above)
Comment (olegmoz) [reply src/test/java/com/artipie/nuget/NuspecTest.java]: @Sammers21 thanks for clarification, it's good to have it here then

File: src/test/java/com/artipie/nuget/NuspecTest.java (hunk 2 above)
Comment (olegmoz) [reply src/test/java/com/artipie/nuget/NuspecTest.java]: @Sammers21 I don't like this rule about not using `+` with strings either. Though I am not in position to change code style in the project. The checks could be disabled in some special cases, but I do not see anything special here.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks for update, the issue with code formatting still stands

**Comment by Sammers21** [comment]
@olegmoz, review the PR once again, please.

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks, approved

**Comment by Sammers21** [comment]
@olegmoz, release a new version please
